services:
  database:
    image: postgres
    restart: always
    container_name: postgres
    environment:
      POSTGRES_DB: orders
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker-postgres
    environment:
      PORT: ${PORT:-3000}
    ports:
      - "3000:3000"
    depends_on:
      - database
    volumes:
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - "5050:80"
    depends_on:
      - database
    volumes:
      - pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
